[package]
name = "demo-stm32h573i-dk"
version = "0.1.0"
edition = "2021"
build = "../common/build.rs"

[[bin]]
name = "demo-stm32h573i-dk"
path = "src/main.rs"
test = false
bench = false

[features]
log-rtt = ["rtt-target"]

[dependencies]
cfg-if = "1.0.0"
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
log = { version = "0.4.29" }
panic-probe = { version = "0.3" }
rtt-target = { version = "0.5.0", optional = true }

stm32h5xx-hal = { path = "../../3rd/stm32h5xx-hal", default-features = false, features = ["stm32h573", "rt"] }
