[package]
name = "demo-cortex-m55"
version = "0.1.0"
edition = "2021"
build = "../common/build.rs"

[[bin]]
name = "demo-cortex-m55"
path = "../common/src/arm_m/main.rs"
test = false
bench = false

[dependencies]
cortex-m    = { version = "0.7", features = ["critical-section-single-core"], optional = false }
cortex-m-rt = { version = "0.7", optional = false }
cortex-m-semihosting = "0.5"
panic-semihosting = "0.6"
