[package]
name = "cortex-m3"
version = "0.1.0"
edition = "2021"
build = "../common/build.rs"

[[bin]]
name = "cortex-m3-tests"
path = "../common/src/arm_m/tests.rs"
test = false
bench = false

[[bin]]
name = "cortex-m3-bench"
path = "../common/src/arm_m/bench.rs"
test = false
bench = false

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-semihosting = "0.6"
keccak-test = { path = "../../keccak/test", features = ["semihosting-log"] }
runtime-common = { path = "../common" }
